### ISSUE TITLE
Shift right doesn't set carry if more than one bit is on

### ISSUE THREAD

**Issue by jocscott** [vladcc/but-how-do-it-know#1]
in shr(void), this line:
	regs[CF] = ( (tmp > 0) && ((tmp >> 1) == 0) );
only sets carry if the low bit in tmp is the only bit that is on.
probably should be:
      regs[CF] = ((tmp & 0x01) > 0);

**Comment by vladcc** [comment]
Thanks!
Fixed.

**Comment by vladcc** [comment]
Should've closed it after the fix, but hey, better late than never.
